name: Vulnerability Static Test
on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  
        uses: actions/checkout@v2
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'rootfs'
          severity: 'CRITICAL'
          ignore-unfixed: true
      - name: Run Grype Vulnerability Scanner
        run: | 
          echo -e '"Package","Version Installed","Vulnerability ID","Severity"\n{{- range .Matches}}\n"{{.Artifact.Name}}","{{.Artifact.Version}}","{{.Vulnerability.ID}}","{{.Vulnerability.Severity}}"\n{{- end}}' > /tmp/CSV.tmpl 
          echo 'INFO >> Staring '
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
          grype version
          echo 'INFO > VULNERABILITY'
          grype dir:${GITHUB_WORKSPACE} -o template -t /tmp/CSV.tmpl > ${GITHUB_WORKSPACE}/report.csv 
          cat ${GITHUB_WORKSPACE}/report.csv 
          echo 'INFO > END'  
          
      - name: Upload to GoogleDrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          filename: "${{ github.workspace }}/report.csv"
          folderId: "1p_s9FBE39yTFUv9arzAhKR8PRyJapvTc"
          name: "report_vulnerability_${{ github.run_number }}.csv" 
 
